- Key 0: LEFT_RIGHT
- Key 1: UP_DOWN
- Key 2: TURN
- Key 3: NOT_ASSIGNED
- Key 4: NOT_ASSIGNED
- Key 5: NOT_ASSIGNED
- Key 6: NOT_ASSIGNED
- Key 7: NOT_ASSIGNED
- Key 8: NOT_ASSIGNED
- Key 9: NOT_ASSIGNED
- Key 10: NOT_ASSIGNED
- Key 11: NOT_ASSIGNED
- Key 12: NOT_ASSIGNED
- Key 13: NOT_ASSIGNED
- Key 14: NOT_ASSIGNED
- Key 15: NOT_ASSIGNED
- Key 16: NOT_ASSIGNED
- Key 17: NOT_ASSIGNED
- Key 18: NOT_ASSIGNED
